### ISSUE TITLE
Erreur pour le panneau Interdiction de dépasser

### ISSUE THREAD

**Issue by petiard** [cpierquet/PanneauxRoute#1]
Bonjour

Merci pour ce boulot !
Je signale une erreur dans la doc : le panneau Interdiction de dépasser n'est pas correct. Dans le fichier .tex, il est appelé par \PanneauTableau{B31} alors que ce devrait être \PanneauTableau{B3}.

Cordialement

**Comment by cpierquet** [comment]
Bonjour, désolé pour la réponse tardive, je viens juste de voir votre message !
Je corrigerai pour la future version.

Cdlt-
